type: object
title: product
required:
  - name
  - unit_price
  - quantity
properties:
  name:
    type: string
    example: "Box of Cohiba"
    description: "The name of the item. It will be displayed in the order."

  unit_price:
    type: integer
    format: int32
    example: 20000
    minimum: 0
    description: "The price of the item in cents."

  quantity:
    type: integer
    format: int32
    example: 1
    minimum: 1
    description: "The quantity of the item in the order."

  sku:
    type: string
    example: "XYZ12345"
    description: "The stock keeping unit for the item. It is used to identify the item in the order."

  brand:
    type: string
    example: "Cohiba"
    description: "The brand of the item."

  description:
    type: string
    example: "Imported From Mex."
    maxLength: 250
    description: "Short description of the item"

  tags:
    type: array
    description: "List of tags for the item. It is used to identify the item in the order."
    minItems: 1
    items:
      type: string
      minLength: 2
      maxLength: 249

  metadata:
    type: object
    maxProperties: 100
    description: >
      Arbitrary key-value data for your internal use. Keys should be strings; values can be any JSON value.
    additionalProperties: true
    example:
      key: "value"